# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rw_Metropolis_c <- function(x0, sigma, N) {
    .Call('_StatComp20079_rw_Metropolis_c', PACKAGE = 'StatComp20079', x0, sigma, N)
}

